#!/bin/bash

# Clear cache
chmod 777 /tmp/progressbar-store/*
rm -rf /tmp/progressbar-store/*

if test -e "/tmp/regataos-store/config/snap-version-cache.txt" ; then
	rm -f "/tmp/regataos-store/config/snap-version-cache.txt"
	echo "" > /tmp/apps-scripts/update-snap-version-cache.txt
fi
