#!/bin/bash

cd /

while :
do

# Create the settings directory
if test -e "/tmp/regataos-configs/config" ; then
	chmod 777 "/tmp/regataos-configs/config"
else
	mkdir -p "/tmp/regataos-configs/config"
	chmod 777 "/tmp/regataos-configs/config"
fi

# Select language
function lang_clear_cache() {
	# Clear cache
	rm -rf "/opt/regataos-store/installapp"
	rm -rf "/opt/regataos-store/removeapp"
	rm -rf "/opt/regataos-store/www/js/translations/language"
}

function lang_pt_BR() {
	ln -s /opt/regataos-store/scripts/translated-scripts/pt-br/installapp /opt/regataos-store/
	ln -s /opt/regataos-store/scripts/translated-scripts/pt-br/removeapp /opt/regataos-store/
	ln -s /opt/regataos-store/www/js/translations/pt-br /opt/regataos-store/www/js/translations/language
}

function lang_pt_PT() {
	ln -s /opt/regataos-store/scripts/translated-scripts/pt-br/installapp /opt/regataos-store/
	ln -s /opt/regataos-store/scripts/translated-scripts/pt-br/removeapp /opt/regataos-store/
	ln -s /opt/regataos-store/www/js/translations/pt-br /opt/regataos-store/www/js/translations/language
}

function lang_en_US() {
	ln -s /opt/regataos-store/scripts/translated-scripts/en-us/installapp /opt/regataos-store/
	ln -s /opt/regataos-store/scripts/translated-scripts/en-us/removeapp /opt/regataos-store/
	ln -s /opt/regataos-store/www/js/translations/en-us /opt/regataos-store/www/js/translations/language
}

user=$(users | awk '{print $1}')
if test -e "/home/$user/.config/plasma-localerc" ; then
	lang=$(grep -r LANG "/home/$user/.config/plasma-localerc")

	if [[ $lang == *"pt_BR"* ]]; then
		lang_clear_cache
		lang_pt_BR

	elif [[ $lang == *"pt_PT"* ]]; then
		lang_clear_cache
		lang_pt_PT

	elif [[ $lang == *"en_US"* ]]; then
		lang_clear_cache
		lang_en_US

	else
		lang_clear_cache
		lang_en_US
	fi

	break
else
	if test -e "/home/$user/.config/user-dirs.locale" ; then
		lang=$(cat "/home/$user/.config/user-dirs.locale")

		if [[ $lang == *"pt_BR"* ]]; then
			lang_clear_cache
			lang_pt_BR

		elif [[ $lang == *"pt_PT"* ]]; then
			lang_clear_cache
			lang_pt_PT

		elif [[ $lang == *"en_US"* ]]; then
			lang_clear_cache
			lang_en_US

		else
			lang_clear_cache
			lang_en_US
		fi

		break
	fi
fi

   sleep 1
done
