#!/bin/bash

cd /

while :
do

# Check if the OS Store Regatta is running
ps -C "regataosstore /opt/regataos-store" > /dev/null
if [ $? = 0 ]
then

# Capture progress for JavaScript (RPM)
if test -e /tmp/progressbar-store/download-percentage ; then

	lines=$(wc -l /tmp/progressbar-store/download-percentage | cut -d"/" -f -1)
	if [ $lines -ge 10 ]; then

		# Progress bar and percentage
		progress=$(tail -2 /tmp/progressbar-store/download-percentage | awk '{print $7}' | head -1 | tail -1)

		if [[ $progress == *"salvo"* ]]; then
			rm -f "/tmp/progressbar-store/speed"
			echo "100%" > /tmp/progressbar-store/progress
		elif [[ $progress == *"saved"* ]]; then
			rm -f "/tmp/progressbar-store/speed"
			echo "100%" > /tmp/progressbar-store/progress
		else
			echo $progress > /tmp/progressbar-store/progress
		fi

		# Internet connection speed and estimated time of conclusion
		check_progress=$(grep -r 100% /tmp/progressbar-store/download-percentage)

		if [[ $check_progress == *"100%"* ]]; then
			rm -f "/tmp/progressbar-store/speed"
			rm -f "/tmp/progressbar-store/eta"
		else
			speed=$(tail -2 /tmp/progressbar-store/download-percentage | awk '{print $8}' | head -1 | tail -1 | sed 's,M, MB/s,' | sed 's,K, KB/s,' | sed 's,G, GB/s,')
			echo $speed > /tmp/progressbar-store/speed
			eta=$(tail -2 /tmp/progressbar-store/download-percentage | awk '{print $9}' | head -1 | tail -1 | sed 's/h/h /' | sed 's/m/m /' | sed 's/s/s /')
			echo $eta > /tmp/progressbar-store/eta
		fi

		# Download Size
		download_size=$(grep -r "\[application" "/tmp/progressbar-store/download-percentage" | head -1 | tail -1 | cut -d":" -f 2- | cut -d"(" -f 2- | cut -d")" -f -1 | sed 's/M/ MB/' | sed 's/K/ KB/' | sed 's/G/ GB/')
		download_size2=$(grep -r "\[application" "/tmp/progressbar-store/download-percentage" | head -1 | tail -1 | cut -d":" -f 2- | cut -d"(" -f 2- | cut -d")" -f -1 | sed 's/M/' | sed 's/K/' | sed 's/G/')
		echo "$download_size" > /tmp/progressbar-store/download-size

		# Downloading File Size
		echo "$progress /" > /tmp/progressbar-store/file-size

		# Get Wget PID
		get_pid=$(cat /tmp/progressbar-store/get-pid)
		pid=$(ps -C "$get_pid" | awk '{print $1}'| tail -1)
		echo $pid > /tmp/progressbar-store/wget-pid

	fi
fi

else
	echo "Nothing to do..."
	break
fi

   sleep 1
done
