#!/bin/bash

cd /

while :
do

# Check if the OS Store Regatta is running
ps -C "magma /opt/regataos-store" > /dev/null
if [ $? = 0 ]; then
	function start_installation() {
		#Check the default language
		checkLocaleFile=$(cat /tmp/regataos-configs/config/plasma-localerc)

		if [[ $checkLocaleFile == *"LANGUAGE"* ]]; then
			lang=$(grep -r LANGUAGE /tmp/regataos-configs/config/plasma-localerc | sed 's/:\|\./ /g' | awk '{print $1}' | cut -d"=" -f 2- | sed 's/_/-/' | tr 'A-Z' 'a-z')

		elif [[ $checkLocaleFile == *"LANG"* ]]; then
			lang=$(grep -r LANG /tmp/regataos-configs/config/plasma-localerc | cut -d"=" -f 2- | sed 's/:\|\./ /g' | awk '{print $1}' | sed 's/_/-/' | tr 'A-Z' 'a-z')

		else
			lang="en-us"
		fi

		progressbar_dir="/tmp/progressbar-store"

		# Make sure there are no critical installation errors
		if test ! -e "$progressbar_dir/installing" ; then
			# Check process queue and sort by sequence
			if test -e "$progressbar_dir/queued-process" ; then
				check_process=$(cat $progressbar_dir/queued-process | head -1 | tail -1 | cut -d"=" -f 2-)

				if [[ $check_process == *"install"* ]]; then
					run_process=$(cat $progressbar_dir/queued-process | head -1 | tail -1 | cut -d"=" -f -1)

					sed -i 1d "$progressbar_dir/queued-process"

					export name=$(grep -r '"name":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export nickname=$(grep -r '"nickname":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export package=$(grep -r '"package":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export package_manager=$(grep -r '"package_manager":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export extra_packages=$(grep -r '"extra_packages":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export architecture=$(grep -r '"architecture":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export repository_name=$(grep -r '"repository_name":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export repository_url=$(grep -r '"repository_url":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export download_link=$(grep -r '"download_link":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');

					sudo -E /opt/regataos-store/scripts/translated-scripts/$lang/installapp/installapp-$package_manager start

				elif [[ $check_process == *"remove"* ]]; then
					# Clear cache
					rm -f $progressbar_dir/download-percentage
					rm -f $progressbar_dir/download-size
					rm -f $progressbar_dir/download-speed
					rm -f $progressbar_dir/file-size
					rm -f $progressbar_dir/eta

					run_process=$(cat $progressbar_dir/queued-process | head -1 | tail -1 | cut -d"=" -f -1)

					sed -i 1d "$progressbar_dir/queued-process"

					export name=$(grep -r '"name":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export nickname=$(grep -r '"nickname":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export package=$(grep -r '"package":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export package_manager=$(grep -r '"package_manager":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export extra_packages=$(grep -r '"extra_packages":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export architecture=$(grep -r '"architecture":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export repository_name=$(grep -r '"repository_name":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export repository_url=$(grep -r '"repository_url":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');
					export download_link=$(grep -r '"download_link":' "/opt/regataos-store/apps-list/$run_process.json" | cut -d":" -f 2- | sed 's/ //' | sed 's/"\|,//g');

					sudo -E /opt/regataos-store/scripts/translated-scripts/$lang/removeapp/removeapp-$package_manager start

				else
					echo "Nothing to do."
				fi
			fi
		fi
	}

	ps -C zypper > /dev/null
	if [ $? = 0 ]; then
		ps -C rpm > /dev/null
		if [ $? = 0 ]; then
			echo "Nothing to do..."
		else
			killall zypper
			start_installation
		fi

	else
		ps -C yast2 > /dev/null
		if [ $? = 0 ]; then
			echo "Nothing to do..."
		else
			start_installation
		fi
	fi

else
	echo "Nothing to do..."
	break
fi

   sleep 1
done
